spring:
  redis:
    database: 0
    host: redis.seiyaya.com
    port: 6388
    password:
    timeout: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
